"""Report generation — renders an agent result as Markdown or JSON."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

SEVERITY_ORDER = ["Critical", "High", "Medium", "Low", "Info"]


def to_markdown(result: dict[str, Any]) -> str:
    findings = result.get("findings", {})
    attack = result.get("attack_mapping", {})
    plan = result.get("plan", [])

    lines: list[str] = []
    a = lines.append

    a("# SecAgent Assessment Report")
    a("")
    a(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    a(f"**Steps used:** {result.get('steps', 0)}")
    a(f"**Tool calls:** {result.get('observations', 0)}")
    a("")

    # Fundings at a glance
    a("## Summary")
    a("")
    if findings.get("flags"):
        a(f"> 🚩 **FLAGS: {', '.join(findings['flags'])}**")
        a("")
    a(f"- Open ports: {_fmt(findings.get('open_ports'))}")
    a(f"- Services: {_fmt(findings.get('services'))}")
    a(f"- Technologies: {_fmt(findings.get('technologies'))}")
    a(f"- Missing security headers: {_fmt(findings.get('missing_headers'))}")
    a(f"- Interesting paths: {_fmt(findings.get('interesting_paths'))}")
    a("")

    # Plan execution
    if plan:
        a("## Plan execution")
        a("")
        a("| # | Task | Status | Intrusive |")
        a("|---|------|--------|-----------|")
        for t in plan:
            a(
                f"| {t.get('id')} | {t.get('task')} | {t.get('status', '?')} "
                f"| {'yes' if t.get('intrusive') else 'no'} |"
            )
        a("")

    # ATT&CK mapping
    if attack.get("techniques"):
        a("## MITRE ATT&CK techniques observed")
        a("")
        a("| ID | Technique | Tactic |")
        a("|----|-----------|--------|")
        for t in attack["techniques"]:
            a(f"| {t['id']} | {t['name']} | {t['tactic']} |")
        a("")

    # Weaknesses
    if attack.get("weaknesses"):
        a("## Configuration weaknesses")
        a("")
        for w in attack["weaknesses"]:
            a(f"- **{w['header']}** — {w['note']}")
        a("")

    # Agent narrative
    a("## Agent report")
    a("")
    a(result.get("report", "(none)"))
    a("")

    a("---")
    a("")
    a("*Generated by SecAgent — for authorized security testing only.*")

    return "\n".join(lines)


def _fmt(vals: Any, limit: int = 20) -> str:
    if not vals:
        return "(none)"
    vals = list(vals)
    shown = ", ".join(str(v) for v in vals[:limit])
    if len(vals) > limit:
        shown += f" ... (+{len(vals) - limit} more)"
    return shown


def to_json(result: dict[str, Any]) -> str:
    return json.dumps(result, ensure_ascii=False, indent=2)


def save(result: dict[str, Any], path: str | Path, fmt: str = "md") -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    content = to_markdown(result) if fmt == "md" else to_json(result)
    path.write_text(content, encoding="utf-8")
    return path
